spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.51:3306/login
    username: ohgiraffers
    password: ohgiraffers

mybatis:
  mapper-locations: mapper/**/*.xml
